spring:
  datasource:
    password: 123
  data:
    redis:
      host: localhost
      port: 6379
app:
  cookie:
    key:
      refreshToken: refresh_token
    defaultValue:
      refreshToken: empty
  host: http://localhost
  service:
    notification:
      url: http://localhost:8084