server:
  port: 8081
spring:
  web:
    resources:
      static-locations: ./uploads/
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: spring-music-player
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:music-player}
    username: ${MYSQL_USER:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    allowed:
      origins:
        - ${app.host}:8082
        - ${app.host}:8088
        - ${app.host}:8090
        - ${app.host}:8090
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Authorization
        - Content-Type
        - Accept
        - Origin
        - X-Requested-With
    oauth2:
      client:
        registration:
          google:
            client-id: 897537541683-7ikcdbpl9c00tfcgbtu10dfu8si2gav4.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  base64-secret: 1KYM6Qp2S8084HQLp+weSBZkZLhs73NkTMoJeql5Gxc7iSUHP/xEtT719zB6XQMilF2R89alaiX8PQl6VXfAhQ==
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 8640000

app:
  whitelist:
    - /api/v1/auth/login
    - /api/v1/auth/check-before-register
    - /api/v1/auth/register
    - /api/v1/auth/account
    - /api/v1/auth/refresh-token
    - /api/v1/auth/login-google-mobile
    - /api/v1/auth/login-google-web
    - /api/v1/auth/password/forgot
    - /api/v1/auth/password/reset
    - /swagger-ui.html
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-ui/**
    - /oauth2/**
    - /auth/**
    - /auth/google
    - /upload
    - /api/v1/change-pass-word
  cookie:
    key:
      refreshToken: refresh_token
    defaultValue:
      refreshToken: empty
  host: ${HOST:localhost}
  otp:
    length: 6
    expiration: 600000
    max-try: 5
    resend:
      expiration: 1440000
      max-try: 3
