INSERT INTO genres (name, description, created_at)
VALUES ('Pop', 'A genre characterized by its catchy melodies and wide appeal.', '2024-01-01 10:00:00'),
       ('Rock', 'A genre that originated in the 1950s, known for its use of electric guitars.', '2024-01-01 11:00:00'),
       ('Jazz', 'A genre that originated in the African-American communities, known for its swing and blue notes.',
        '2024-01-01 12:00:00'),
       ('Classical', 'A genre of music that is rooted in the traditions of Western art music.', '2024-01-01 13:00:00'),
       ('Hip Hop', 'A genre that originated in the 1970s, characterized by rhythmic vocal style and DJing.',
        '2024-01-01 14:00:00'),
       ('Country',
        'A genre that originated in the southern United States, known for its storytelling and simple chord progressions.',
        '2024-01-01 15:00:00'),
       ('Reggae',
        'A music genre that originated in Jamaica, known for its offbeat rhythm and socially conscious lyrics.',
        '2024-01-01 16:00:00'),
       ('Blues',
        'A genre that originated in the African-American communities of the Deep South, characterized by its use of specific chord progressions.',
        '2024-01-01 17:00:00'),
       ('Metal', 'A genre characterized by heavy use of electric guitars and aggressive vocals.',
        '2024-01-01 18:00:00'),
       ('Electronic', 'A genre that employs electronic musical instruments and technology in its production.',
        '2024-01-01 19:00:00'),
       ('Indie', 'A genre that encompasses music produced independently from major commercial record labels.',
        '2024-01-01 20:00:00');
